hmcts/prl-citizen-frontend

package.json
yarn.lock

Fix master build

---

package.json

Fix for master build

---

src/main/steps/applicant/task-list/content.test.ts
src/main/steps/applicant/task-list/content.ts
src/main/steps/applicant/task-list/template.njk
src/main/steps/applicant/task-list/utils.ts
src/main/steps/common/common.content.ts
src/main/steps/respondent/task-list/content.test.ts
src/main/steps/respondent/task-list/utils.ts

initial commit

---

package.json
yarn.lock

Fixed dependency error

---

charts/prl-citizen-frontend/Chart.yaml

Chart version update

---

src/main/app/case/case.ts
src/main/app/controller/GetController.ts
src/main/modules/nunjucks/index.ts
src/main/steps/c100-rebuild/confidentiality/feedback/template.njk
src/main/steps/c100-rebuild/confidentiality/start-alternative/content.test.ts
src/main/steps/c100-rebuild/confidentiality/start-alternative/content.ts

added different variable name and screen data

---

src/main/app/form/Form.ts
src/main/modules/nunjucks/index.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/template.njk
src/main/steps/urls.ts

feat: implement reasonable adjustments hearingType screen(PRLC100-48)

---

src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.ts

fix: continue button label change

---

src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.ts

Fixed error scenarios

---

Jenkinsfile_CNP
Jenkinsfile_nightly
config/custom-environment-variables.yaml
config/default.yaml
config/development.yaml
src/main/app/auth/user/oidc.ts
src/main/modules/properties-volume/index.ts

Fixing issue with the azure secret fetch logic

---

src/main/steps/applicant/support-you-need-during-case/summary/content.ts
src/main/steps/applicant/support-you-need-during-case/summary/utils.test.ts
src/main/steps/applicant/support-you-need-during-case/summary/utils.ts

Fix for merge conflict issues

---

src/main/app/case/case.ts
src/main/steps/c100-rebuild/PageStepConfigurator.test.ts
src/main/steps/c100-rebuild/PageStepConfigurator.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/pageStepConfig.ts
src/main/steps/c100-rebuild/reasonable-adjustments/communication-help/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/communication-help/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/template.njk
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/template.njk
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/template.njk
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/template.njk
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/template.njk
src/main/steps/urls.ts

…onfig class and add test cases
```
[ ] Yes
[ ] No
```

feat(PRLC100-75): Integrate Reasonable Adjustments, create  PageStepConfig class and add test cases

---

config/default.yaml
config/development.yaml
src/main/app/auth/user/oidc.ts
src/main/app/case/CosApiClient.ts
src/main/app/controller/PostController.ts
src/main/modules/properties-volume/index.ts
src/main/steps/applicant/confirm-contact-details/checkanswers/content.ts

Its working for now

---

src/main/app/document/DocumentManagementController.ts
src/main/routes.ts
src/main/steps/applicant/yourdocuments/alldocuments/drug_alcohol_tests/content.ts
src/main/steps/applicant/yourdocuments/alldocuments/drug_alcohol_tests/template.njk
src/main/steps/applicant/yourdocuments/alldocuments/paternity_test_reports/content.ts
src/main/steps/applicant/yourdocuments/alldocuments/paternity_test_reports/template.njk
src/main/steps/respondent/yourdocuments/alldocuments/drug_alcohol_tests/content.ts
src/main/steps/respondent/yourdocuments/alldocuments/drug_alcohol_tests/template.njk
src/main/steps/respondent/yourdocuments/alldocuments/paternity_test_reports/content.ts
src/main/steps/respondent/yourdocuments/alldocuments/paternity_test_reports/template.njk

download drug and paternity docs

---

src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts

Drug paternity tasklist hide

---

.husky/pre-commit

feat(git-commit-automation): Automate git commit process

---

src/main/steps/c100-rebuild/typeoforder/caorder/content.test.ts
src/main/steps/c100-rebuild/typeoforder/caorder/content.ts

Validation changes

---

src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/confirmation-page/content.test.ts
src/main/steps/c100-rebuild/confirmation-page/content.ts
src/main/steps/c100-rebuild/confirmation-page/template.njk
src/main/steps/urls.ts

issue fixes for testing

---

src/main/steps/c100-rebuild/international-elements/jurisdiction/content.test.ts
src/main/steps/c100-rebuild/international-elements/jurisdiction/content.ts
src/main/steps/c100-rebuild/international-elements/parents/content.test.ts
src/main/steps/c100-rebuild/international-elements/parents/content.ts
src/main/steps/c100-rebuild/international-elements/request/content.test.ts
src/main/steps/c100-rebuild/international-elements/request/content.ts
src/main/steps/c100-rebuild/international-elements/start/content.test.ts
src/main/steps/c100-rebuild/international-elements/start/content.ts
src/main/steps/c100-rebuild/start/content.test.ts
src/main/steps/c100-rebuild/start/content.ts

https://tools.hmcts.net/jira/browse/PRLC100-117
https://tools.hmcts.net/jira/browse/PRLC100-116
```
[ ] Yes
[ ] No
```

c100 Rebuild - updated contents for international elements post feedback from Legal n Policy

---

src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/document-submission/content.test.ts
src/main/steps/c100-rebuild/document-submission/content.ts
src/main/steps/c100-rebuild/document-submission/template.njk
src/main/steps/urls.ts

feat(PRLC100-106) Document Submission screen

---

src/main/server.ts

trying to fix the error

---

src/main/app/case/case.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/miam/urgency/content.test.ts
src/main/steps/c100-rebuild/miam/urgency/content.ts
src/main/steps/c100-rebuild/miam/urgency/template.njk
src/main/steps/urls.ts

PLRC100-186 changes

---

src/main/app/case/case.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/miam/valid-reason/content.test.ts
src/main/steps/c100-rebuild/miam/valid-reason/content.ts
src/main/steps/c100-rebuild/miam/valid-reason/template.njk
src/main/steps/urls.ts

feature-PRLC100-180 feature changes

---

src/main/steps/c100-rebuild/miam/miam-info/content.test.ts
src/main/steps/c100-rebuild/miam/miam-info/content.ts

fix: address test feedback for link and MIAM abbrievation(PRLC100-173)

---

src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/miam/miam-other/content.test.ts
src/main/steps/c100-rebuild/miam/miam-other/content.ts
src/main/steps/c100-rebuild/miam/miam-other/template.njk
src/main/steps/urls.ts

feat: implement MIAM other valid reasons screen(PRLC100-188)

---

src/main/steps/c100-rebuild/safety-concerns/applicant/report-abuse/content.test.ts
src/main/steps/c100-rebuild/safety-concerns/applicant/report-abuse/content.ts

PRLC100-160: Update translations

---

src/main/app/auth/user/oidc.ts
src/main/steps/respondent/task-list/tasklist-items.ts
src/main/steps/respondent/task-list/tasklist.ts
src/main/steps/tasklistresponse/responseCaseSequence.test.ts
src/main/steps/tasklistresponse/responseCaseSequence.ts

fixing issues relates to response tasklist

---

src/main/steps/c100-rebuild/miam/miam-other/content.test.ts
src/main/steps/c100-rebuild/miam/miam-other/content.ts

fix: correct text messages on screen(PRLC100-188)

---

src/main/steps/c100-rebuild/safety-concerns/applicant/report-abuse/content.test.ts
src/main/steps/c100-rebuild/safety-concerns/applicant/report-abuse/content.ts
src/main/steps/c100-rebuild/safety-concerns/child/report-abuse/content.test.ts
src/main/steps/c100-rebuild/safety-concerns/child/report-abuse/content.ts
src/main/steps/c100-rebuild/safety-concerns/concern-guidance/content.test.ts
src/main/steps/c100-rebuild/safety-concerns/concerns-for-safety/content.test.ts
src/main/steps/c100-rebuild/safety-concerns/concerns-for-safety/content.ts
src/main/steps/c100-rebuild/typeoforder/shortstatement/content.test.ts
src/main/steps/c100-rebuild/typeoforder/shortstatement/content.ts

Code coverage/plrc100 219 safety concerns

---

src/main/steps/c100-rebuild/hearing-urgency/urgent-details/content.test.ts
src/main/steps/c100-rebuild/hearing-urgency/urgent-details/content.ts

https://tools.hmcts.net/jira/browse/PRLC100-195
C100 Rebuild - tell us about your situation
```
[ ] Yes
[ ] No
```

RESOLVING QA COMMENTS

---

src/main/modules/oidc/index.ts

fix-Speed up app rendering

---

charts/prl-citizen-frontend/Chart.yaml

https://tools.hmcts.net/jira/browse/PRL-2392
```
[ ] Yes
[ ] No
```

Renovate/idam pr 2.x

---

src/main/app/address/ManualAddressPostControllerBase.ts

Confirm contact details - refactor Address LookUp

---

src/main/app/controller/GetController.ts
src/main/steps/common/common.content.ts

Fixed common issues in the framework.
1. Changed the error message header in the banner to "There is a problem"
2. Fixed the caption not rendering issue for c100 rebuild.
```
[ ] Yes
[ ] No
```

Common Framework fixes - Changed the error message header & fixed caption issue

---

src/main/steps/c100-rebuild/safety-concerns/other-concerns/drugs/content.test.ts
src/main/steps/c100-rebuild/safety-concerns/other-concerns/drugs/content.ts

fix(PLRC100-128) fix : error msg fix

---

src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.test.ts
src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.ts
src/main/steps/c100-rebuild/applicant/address/lookup/content.test.ts
src/main/steps/c100-rebuild/applicant/address/lookup/content.ts
src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.test.ts
src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.ts
src/main/steps/c100-rebuild/applicant/address/manual/content.test.ts
src/main/steps/c100-rebuild/applicant/address/manual/content.ts
src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.test.ts
src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.ts
src/main/steps/c100-rebuild/applicant/address/select/content.test.ts
src/main/steps/c100-rebuild/applicant/address/select/content.ts
src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.ts
src/main/steps/c100-rebuild/applicant/confidentiality/details-know/postContoller.ts
src/main/steps/c100-rebuild/applicant/confidentiality/details-know/postController.test.ts
src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.test.ts
src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.ts
src/main/steps/c100-rebuild/applicant/confidentiality/feedback/postController.ts
src/main/steps/c100-rebuild/applicant/confidentiality/feedbackno/content.ts
src/main/steps/c100-rebuild/applicant/confidentiality/feedbackno/postController.ts
src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/content.test.ts
src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/content.ts
src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/postController.ts
src/main/steps/c100-rebuild/applicant/confidentiality/start/content.ts
src/main/steps/c100-rebuild/applicant/confidentiality/start/postController.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/urls.ts

…applicant journey
```
[ ] Yes
[ ] No
```

feat(PRLC100-307,PRLC100-308): Change query params to URL params for applicant journey

---

src/main/steps/privacy-policy/content.ts
src/main/steps/privacy-policy/template.njk
src/main/steps/terms-and-conditions/content.test.ts
src/main/steps/terms-and-conditions/content.ts
src/main/steps/terms-and-conditions/template.njk

https://tools.hmcts.net/jira/browse/PRL-2497
Updated Terms and Conditions
```
[ ] Yes
[ x] No
```

PRL-2497 Terms and Conditions

---

src/main/steps/privacy-policy/content.test.ts
src/main/steps/privacy-policy/content.ts
src/main/steps/privacy-policy/template.njk

https://tools.hmcts.net/jira/browse/PRL-2498
update privacy policy to match prl-2498
```
[ ] Yes
[ x] No
```

PRL-2497 Privacy Policy

---

config/development.yaml
src/main/app/case/definition.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/child-details/live-with/content.test.ts
src/main/steps/c100-rebuild/child-details/live-with/content.ts
src/main/steps/c100-rebuild/child-details/live-with/postController.test.ts
src/main/steps/c100-rebuild/child-details/live-with/postController.ts
src/main/steps/c100-rebuild/child-details/live-with/routeGuard.test.ts
src/main/steps/c100-rebuild/child-details/live-with/routeGuard.ts
src/main/steps/c100-rebuild/child-details/live-with/template.njk
src/main/steps/c100-rebuild/child-details/navigationController.test.ts
src/main/steps/c100-rebuild/child-details/navigationController.ts
src/main/steps/c100-rebuild/child-details/util.ts
src/main/steps/c100-rebuild/respondent-details/navigationController.test.ts
src/main/steps/common/string-parser.ts
src/main/steps/urls.ts
src/test/unit/mocks/mocked-requests/child-details-mock.ts
src/test/unit/mocks/mocked-requests/people-mock.ts

feat(PRLC100-38): Add who child live with screen

---

src/main/app/case/C100CaseApi.ts
src/main/steps/c100-rebuild/childaddress/content.test.ts
src/main/steps/c100-rebuild/childaddress/content.ts
src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.test.ts
src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.ts
src/main/steps/c100-rebuild/help-with-fees/hwf-guidance/content.test.ts
src/main/steps/c100-rebuild/help-with-fees/hwf-guidance/content.ts
src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/content.test.ts
src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/content.ts
src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/getController.ts

C100-Rebuild - Added CCD fields for mappers

---

src/main/app/case/case.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/child-details/has-other-children/content.test.ts
src/main/steps/c100-rebuild/child-details/has-other-children/content.ts
src/main/steps/c100-rebuild/child-details/other-children/names/content.test.ts
src/main/steps/c100-rebuild/child-details/other-children/names/content.ts
src/main/steps/c100-rebuild/child-details/other-children/names/postContoller.ts
src/main/steps/c100-rebuild/child-details/other-children/names/postController.test.ts
src/main/steps/c100-rebuild/child-details/other-children/navigationController.test.ts
src/main/steps/c100-rebuild/child-details/other-children/navigationController.ts
src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.test.ts
src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.ts
src/main/steps/c100-rebuild/child-details/other-children/personal-details/postController.test.ts
src/main/steps/c100-rebuild/child-details/other-children/personal-details/postController.ts
src/main/steps/c100-rebuild/child-details/other-children/routeGuard.test.ts
src/main/steps/c100-rebuild/child-details/other-children/routeGuard.ts
src/main/steps/c100-rebuild/child-details/util.test.ts
src/test/unit/mocks/mocked-requests/other-child-mock.ts

PRLC100-293
```
[ ] Yes
[ ] No
```

C100-Rebuild - Renamed other children prefix to ocd

---

src/main/app/case/definition.ts
src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.ts
src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.ts
src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.ts
src/main/steps/c100-rebuild/applicant/navigationController.test.ts
src/main/steps/c100-rebuild/applicant/navigationController.ts
src/main/steps/c100-rebuild/applicant/relationship-to-child/content.test.ts
src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
src/main/steps/c100-rebuild/applicant/relationship-to-child/postController.ts
src/main/steps/c100-rebuild/applicant/relationship-to-child/template.njk
src/main/steps/c100-rebuild/applicant/util.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/urls.ts
src/test/unit/mocks/mocked-requests/applicant-details-mock.ts

https://tools.hmcts.net/jira/browse/PRLC100-26
```
[ ] Yes
[ ] No
```

PRLC100-26 - Added screen changes for applicant relationshop to child

---

src/main/app/case/case.ts
src/main/app/case/definition.ts
src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
src/main/steps/c100-rebuild/applicant/confidentiality/common/postController.test.ts
src/main/steps/c100-rebuild/applicant/personal-details/content.test.ts
src/main/steps/c100-rebuild/applicant/personal-details/content.ts
src/main/steps/c100-rebuild/applicant/personal-details/postController.test.ts
src/main/steps/c100-rebuild/applicant/personal-details/postController.ts
src/main/steps/c100-rebuild/applicant/personal-details/template.njk
src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
src/main/steps/c100-rebuild/applicant/util.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/urls.ts

feat(PLRC100-25) add:Applicant Personal Details

---

src/main/app/case/definition.ts
src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
src/main/steps/c100-rebuild/applicant/contact-detail/content.test.ts
src/main/steps/c100-rebuild/applicant/contact-detail/content.ts
src/main/steps/c100-rebuild/applicant/contact-detail/postController.test.ts
src/main/steps/c100-rebuild/applicant/contact-detail/postController.ts
src/main/steps/c100-rebuild/applicant/contact-detail/template.njk
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/urls.ts

feat: implement applicant contact detail screen(PRLC100-29)

---

src/main/app/case/definition.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/other-person-details/address/lookup/AddressLookupPostController.ts
src/main/steps/c100-rebuild/other-person-details/address/lookup/content.ts
src/main/steps/c100-rebuild/other-person-details/address/manual/content.test.ts
src/main/steps/c100-rebuild/other-person-details/address/manual/content.ts
src/main/steps/c100-rebuild/other-person-details/address/select/content.test.ts
src/main/steps/c100-rebuild/other-person-details/address/select/content.ts
src/main/steps/c100-rebuild/other-person-details/navigationController.test.ts
src/main/steps/c100-rebuild/other-person-details/navigationController.ts
src/main/steps/c100-rebuild/other-person-details/personal-details/content.test.ts
src/main/steps/c100-rebuild/other-person-details/personal-details/content.ts
src/main/steps/c100-rebuild/other-person-details/personal-details/postController.test.ts
src/main/steps/c100-rebuild/other-person-details/routeGuard.test.ts
src/main/steps/c100-rebuild/other-person-details/util.test.ts
src/main/steps/c100-rebuild/other-person-details/util.ts
src/main/steps/c100-rebuild/people/address/address-lookup.test.ts
src/main/steps/c100-rebuild/people/address/address-lookup.ts
src/main/steps/c100-rebuild/people/address/address-manual.test.ts
src/main/steps/c100-rebuild/people/address/address-manual.ts
src/main/steps/c100-rebuild/people/address/address-select.test.ts
src/main/steps/c100-rebuild/people/address/address-select.ts
src/main/steps/c100-rebuild/respondent-details/contact-details/content.test.ts
src/main/steps/c100-rebuild/respondent-details/contact-details/content.ts
src/main/steps/c100-rebuild/respondent-details/personal-details/content.test.ts
src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
src/main/steps/c100-rebuild/respondent-details/util.ts

https://tools.hmcts.net/jira/browse/PRLC100-288
```
[ ] Yes
[ ] No
```

PRLC100-288 - Added navigation linking for other persons

---

Jenkinsfile_CNP
Jenkinsfile_nightly
charts/prl-citizen-frontend/values.preview.template.yaml
config/custom-environment-variables.yaml
config/default.yaml
config/development.yaml
src/main/app/case/CosApiClient.ts
src/main/modules/oidc/index.ts
src/main/modules/properties-volume/index.ts
src/main/steps/urls.ts

Fixed below issues
1. Fixed Invalid client issue in backend cos APIs
2. Skip linkCases for C100 url & retrieveCases only once when dashboard loads.

PVT-Law - C100-Rebuild common issue fixes

---

src/main/app/case/definition.ts
src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
src/main/steps/c100-rebuild/applicant/contact-detail/content.test.ts
src/main/steps/c100-rebuild/applicant/contact-detail/content.ts
src/main/steps/c100-rebuild/applicant/contact-detail/postController.test.ts
src/main/steps/c100-rebuild/applicant/contact-detail/postController.ts

feat: amend applicant contact details (PRLC100-29)

---

src/main/app/case/definition.ts
src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
src/main/steps/c100-rebuild/applicant/contact-detail/content.test.ts
src/main/steps/c100-rebuild/applicant/contact-detail/content.ts
src/main/steps/c100-rebuild/applicant/contact-detail/postController.ts

feat: remove not providing email address reason(PRLC100-29)

---

src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/other-person-details/navigationController.test.ts
src/main/steps/c100-rebuild/other-person-details/navigationController.ts

https://tools.hmcts.net/jira/browse/PRLC100-284
https://tools.hmcts.net/jira/browse/PRLC100-288
```
[ ] Yes
[ ] No
```

PRLC100-284,PRLC100-288 - Added linking for child lives with screen

---

src/main/steps/c100-rebuild/get-case/getController.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.ts
src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.test.ts
src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.ts

https://tools.hmcts.net/jira/browse/PRLC100-331
```
[ ] Yes
[ ] No
```

PRLC100-331 - Refactored reasonable adjustments sub fields for check your answers screen

---

src/main/app/utils/featureToggles.test.ts

- Increased `featureToggles.test.ts` file test coverage percentage
```
[ ] Yes
[x] No
```

increase test coverage from 80% to 91%

---

src/main/app/case/case.ts
src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/child-details/navigationController.ts
src/main/steps/c100-rebuild/miam/navigationController.ts
src/main/steps/c100-rebuild/other-proceedings/navigationController.ts
src/main/steps/c100-rebuild/people/address/address-manual.ts
src/main/steps/c100-rebuild/people/util.ts
src/main/steps/c100-rebuild/respondent-details/address/manual/content.test.ts
src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts

feat(PRLC100-329): Add alternate flows screen linking

---

src/main/app/fees/fees-lookup-api.test.ts
src/main/app/form/Form.test.ts
src/main/steps/c100-rebuild/applicant/relationship-to-child/postController.test.ts
src/main/steps/c100-rebuild/respondent-details/relationship-to-child/postController.test.ts
src/main/steps/common/string-parser.test.ts

[### JIRA link (if applicable) ###](https://tools.hmcts.net/jira/browse/PRLC100-361)
Files coverage improved:
app/fees/fees-lookup-api.ts
app/form/Form.ts
/string-parser.ts
```
[ ] Yes
[X] No
```

PRLC100-361 C100 Rebuild Improve Code Coverage

---

src/main/steps/c100-rebuild/check-your-answers/content.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/applicantHelper.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/reasonableAdjustment.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/safetyConcernHelper.test.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/satetyConcernHelper.ts
src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
src/main/steps/c100-rebuild/check-your-answers/util/helpWithFee.util.ts
src/main/steps/c100-rebuild/check-your-answers/util/miam.util.test.ts
src/main/steps/c100-rebuild/check-your-answers/util/miam.util.ts
src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.ts

Feature/c100 check your answer/sonar

---

src/main/modules/payments/paymentHelper.test.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/courtOrderHelper.test.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.test.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.test.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/safetyConcernHelper.test.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/satetyConcernHelper.ts
src/main/steps/c100-rebuild/check-your-answers/util/hearingwithout.util.test.ts
src/main/steps/c100-rebuild/check-your-answers/util/hearingwithout.util.ts
src/main/steps/c100-rebuild/check-your-answers/util/miam.util.test.ts
src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.test.ts

Feature/check your answer/test

---

src/main/app/case/C100CaseApi.test.ts
src/main/app/case/C100CaseApi.ts
src/main/app/case/definition.ts
src/main/app/controller/PostController.ts
src/main/modules/payments/paymentController.ts
src/main/steps/c100-rebuild/c100sequence.test.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts

Added changes for submit case for below
1. submit case when help with fees is opted.
2. pay first then submit case when help with fees is not opted in.
https://tools.hmcts.net/jira/browse/PRLC100-344
```
[ ] Yes
[ ] No
```

PRLC100-344 - Submit case/Pay & submit changes

---

src/main/app/case/C100CaseApi.ts
src/main/app/case/case.ts
src/main/modules/payments/paymentApi.test.ts
src/main/modules/payments/paymentApi.ts
src/main/modules/payments/paymentController.ts
src/main/modules/payments/paymentHelper.test.ts
src/main/modules/payments/paymentHelper.ts

PRLC100-344 - Added changes to create only service in case of help with fees

---

config/default.yaml
config/development.yaml
src/main/common/clients/launchDarklyClient.ts
src/main/modules/feature-toggle/index.ts
src/main/modules/oidc/index.ts
src/main/server.ts

added log for c100 rebuild LD flag

---

src/main/app/case/case.ts
src/main/steps/c100-rebuild/applicant/navigationController.ts
src/main/steps/c100-rebuild/c100sequence.ts
src/main/steps/c100-rebuild/child-details/navigationController.ts

fix(PRLC100-365): Fix sonar issues

---

src/main/steps/c100-rebuild/screening-questions/permissions-why/content.test.ts
src/main/steps/c100-rebuild/screening-questions/permissions-why/content.ts

Task: https://tools.hmcts.net/jira/browse/PRLC100-349 
SubTask: https://tools.hmcts.net/jira/browse/PRLC100-359 
- Added hint text on top of text areas
- Fixed error messages correctly displaying respective error message text
```
[ ] Yes
[x] No
```

fix issue - added hint text and fixed error messages

---

src/main/app/case/C100CaseApi.test.ts
src/main/app/case/C100CaseApi.ts

fix: pass caseId in update case (PRLC100-340)

---

src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.test.ts
src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.test.ts

test coverage for Address controller

---

src/main/modules/payments/paymentApi.ts
src/main/modules/payments/paymentController.ts
src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts

PRLC100-344 - Fixed create service payment issue

---

src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.test.ts
src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.ts
src/main/steps/c100-rebuild/child-details/child-matters/content.ts

1. Update case on load of check your answers screen
2. Fix Array issue for Child matters screen
```
[ ] Yes
[ ] No
```

Update case before cya

---

src/main/app/case/C100CaseApi.test.ts
src/main/app/case/C100CaseApi.ts
src/main/app/utils/featureToggles.ts
src/main/modules/oidc/index.ts
src/main/modules/payments/paymentController.ts

https://tools.hmcts.net/jira/browse/PRLC100-344
https://tools.hmcts.net/jira/browse/PRLC100-345
```
[ ] Yes
[ ] No
```

C100 Rebuild - create case & payment issue fixes

---

src/main/modules/payments/paymentController.ts
src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.ts
src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
src/main/steps/c100-rebuild/confirmation-page/template.njk
src/test/unit/mocks/mocked-requests/check-your-answer-flow-1-mock.ts
src/test/unit/mocks/mocked-requests/check-your-answer-flow-2-mock.ts
src/test/unit/mocks/mocked-requests/check-your-answer-flow-3-mock.ts
src/test/unit/mocks/mocked-requests/check-your-answer-flow-4-mock.ts

C100-Rebuild - Fixed payment scenarios issues

---

src/main/steps/c100-rebuild/applicant/contact-preference/content.test.ts
src/main/steps/c100-rebuild/applicant/contact-preference/content.ts

Issues found on: https://tools.hmcts.net/jira/browse/PRLC100-378 
- Fixed the error message to display correct content
- Refactored checkboxes: Digital checkbox option is now disabled, if applicant did not provide their email address
```
[ ] Yes
[x] No
```

fix QA found issues

---

config/default.yaml
src/main/steps/c100-rebuild/check-your-answers/content.ts
src/main/steps/c100-rebuild/check-your-answers/form.njk
src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts

Feature/cosmetic fixes/c100

---

config/default.yaml
src/main/app/controller/PostController.ts
src/main/modules/payments/paymentApi.test.ts
src/main/modules/payments/paymentController.ts
src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.ts

C100 Rebuild - payment issue fixes

---

src/main/app/case/C100CaseApi.ts
src/main/modules/payments/paymentController.ts
src/main/steps/c100-rebuild/confirmation-page/ApplicationDownloadController.ts

feat(PRLC100-408): Add download draft copy of application feature

---

src/main/steps/c100-rebuild/applicant/confidentiality/common/commonConfidentialityPostController.ts

fixed issues with confidentiality issues with applicant

---

src/test/end-to-end/helpers/generalHelper.js

Crossbrowser Nightly build fixes

---

src/main/steps/common/webpack/css-template.njk
src/main/steps/common/webpack/css.njk

fix(PRL-2897): Remove custom.css

---

src/main/steps/common/common.content.ts
src/main/steps/prl-cases/dashboard/DashboardGetController.ts
src/main/steps/prl-cases/dashboard/content.test.ts
src/main/steps/prl-cases/dashboard/content.ts

feat(PRL-2931): Update service name

---

src/main/steps/applicant/task-list/content.test.ts
src/main/steps/applicant/task-list/tasklist.ts
src/main/steps/common/tasklist/template.njk
src/main/steps/respondent/task-list/tasklist.ts

feat(PRL-2842): Update case dashboard to show relevant section for closed state

---

charts/prl-citizen-frontend/Chart.yaml
charts/prl-citizen-frontend/values.preview.template.yaml
config/default.yaml
config/development.yaml

Upgrade node version 3.1

---

charts/prl-citizen-frontend/Chart.yaml

Bump the version

---

src/main/app/case/definition.ts
src/main/app/controller/AppRequest.ts
src/main/routes.test.ts
src/main/routes.ts
src/main/steps/applicant/confirm-contact-details/address/lookup/content.test.ts
src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringCaseController.ts
src/main/steps/applicant/support-you-need-during-case/safety-arrangements/content.ts
src/main/steps/applicant/support-you-need-during-case/summary/content.test.ts
src/main/steps/applicant/support-you-need-during-case/summary/content.ts
src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklist-items-all-documents.ts
src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.test.ts
src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
src/main/steps/c100-rebuild/check-your-answers/content.test.ts
src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.test.ts
src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
src/main/steps/common/controller/ViewAllDocumentsPostController.ts
src/main/steps/common/support-you-need-during-case/summary/utils.test.ts
src/main/steps/common/support-you-need-during-case/summary/utils.ts
src/main/steps/respondent/support-you-need-during-case/summary/content.ts
src/main/steps/respondent/task-list/get.ts
src/main/steps/respondent/task-list/tasklist.ts
src/main/steps/respondent/task-list/utils.ts
src/main/steps/respondent/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/util/safetyConcerns.util.test.ts
src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/util/safetyConcerns.util.ts
src/main/steps/tasklistresponse/support-you-need-during-case/summary/content.ts

fixed bug for support you need at view all docs

---

src/main/steps/common/page.njk

added the private law in title for upload , view all docs

---

charts/prl-citizen-frontend/values.preview.template.yaml
config/default.yaml
config/development.yaml
src/main/steps/c100-rebuild/applicant/address/common/address-manual.test.ts
src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.test.ts
src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.ts
src/main/steps/c100-rebuild/applicant/confidentiality/details-know/template.njk
src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.test.ts
src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.ts
src/main/steps/c100-rebuild/applicant/confidentiality/feedback/template.njk
src/main/steps/c100-rebuild/applicant/confidentiality/start/content.test.ts
src/main/steps/c100-rebuild/applicant/confidentiality/start/content.ts
src/main/steps/c100-rebuild/applicant/confidentiality/start/template.njk
src/main/steps/c100-rebuild/check-your-answers/content.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.ts
src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/content.test.ts
src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/content.ts
src/main/steps/c100-rebuild/safety-concerns/applicant/concerns-about/content.test.ts
src/main/steps/c100-rebuild/safety-concerns/applicant/concerns-about/content.ts
src/main/steps/c100-rebuild/safety-concerns/child/template.njk
src/main/steps/c100-rebuild/safety-concerns/concerns-for-safety/content.test.ts
src/main/steps/c100-rebuild/safety-concerns/concerns-for-safety/content.ts
src/main/steps/c100-rebuild/safety-concerns/orders-required/unsupervised/content.test.ts
src/main/steps/c100-rebuild/safety-concerns/orders-required/unsupervised/content.ts

welsh translation QA fix

---

src/main/app/case/C100CaseApi.test.ts
src/main/app/case/definition.ts
src/main/modules/payments/paymentController.ts

Added a new event for citizen case submit with hwf

---

config/development.yaml
src/main/steps/c100-rebuild/check-your-answers/content.ts
src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts

welsh Translation fixes

---

Jenkinsfile_nightly
charts/prl-citizen-frontend/Chart.yaml

Removed unwanted pact test from nightly build
```
[ ] Yes
[x] No
```

Nightly-fix: Remove unwanted Pact test from Nightly build

---

src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts

c100 - payment stub for case submission

---

src/main/steps/prl-cases/dashboard/tabView.ts

PRL-3156 Issue fix - Fixed issue in the account dashboard for submitted cases

---

Jenkinsfile_CNP
test/java/build.gradle

upgraded gradle to 8.0.1

---

Jenkinsfile_nightly

Cross browser fix

---

src/main/app/case/definition.ts
src/main/app/controller/GetCaseController.ts
src/main/app/controller/PostController.ts
src/main/steps/c100-rebuild/applicant/contact-preference/content.test.ts
src/main/steps/c100-rebuild/applicant/contact-preference/content.ts
src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
src/main/steps/prl-cases/dashboard/content.test.ts
src/main/steps/prl-cases/dashboard/content.ts
src/main/steps/prl-cases/dashboard/tabView.test.ts
src/main/steps/prl-cases/dashboard/tabView.ts
src/main/steps/prl-cases/dashboard/utils.ts

Reverts hmcts/prl-citizen-frontend#816

Revert "c100 - payment stub for case submission"

---

src/main/steps/applicant/contact-preferences/contact-email/content.test.ts
src/main/steps/applicant/contact-preferences/contact-post/contest.test.ts
src/main/steps/applicant/contact-preferences/contact-preferences/contest.test.ts
src/main/steps/c100-rebuild/applicant/contact-preference/content.test.ts
src/main/steps/common/contact-preferences/ContactPreferencesGetController.test.ts
src/main/steps/common/contact-preferences/ContactPreferencesMapper.test.ts
src/main/steps/common/contact-preferences/contact-email/content.test.ts
src/main/steps/common/contact-preferences/contact-post/content.test.ts
src/main/steps/common/contact-preferences/contact-preferences/content.test.ts

Added some test cases to improve test coverage for contact pref 
```
[ ] Yes
[x] No
```

increase test coverage for branch c100-dashboard-tasklist

---

src/main/steps/applicant/applicantCaseSequence.test.ts
src/main/steps/applicant/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
src/main/steps/common/contact-preferences/ContactPreferencesGetController.test.ts
src/main/steps/common/contact-preferences/ContactPreferencesMapper.test.ts
src/main/steps/common/contact-preferences/ContactPreferencesPostController.test.ts

- Added test cases to fix sonar build issues & increase test coverage
```
[ ] Yes
[x] No
```

Increasing coverage to fix sonar build issues

---

src/main/steps/common/breadcrumb/BreadcrumbController.test.ts

https://tools.hmcts.net/jira/browse/PRL-3364 
- added a test file for BreadcrumbController.ts file. 
- Test coverage is now at 100%
```
[ ] Yes
[x] No
```

add BreadcrumbController test file

---

src/main/steps/common/contact-preferences/ContactPreferencesPostController.ts

https://tools.hmcts.net/jira/browse/PRL-3368 
- Refactoring and getting rid of a minor code smell
```
[ ] Yes
[x] No
```

fixing the minor code smell in ContactPreferencesPostController.ts

---

src/main/app/controller/GetController.test.ts

https://tools.hmcts.net/jira/browse/PRL-3381 
Increase code coverage
```
[ ] Yes
[x] No
```

increasing code coverage for getController.ts

---

src/main/steps/common/breadcrumb/content.ts
src/main/steps/common/task-list/components/notification-banner/content.ts
src/main/steps/prl-cases/dashboard/content.ts

tasklist notification banner

---

src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.test.ts
src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.ts
src/main/steps/common/task-list/components/progress-bar/content.ts
src/main/steps/common/task-list/components/side-links/content.ts
src/main/steps/common/task-list/content.test.ts
src/main/steps/prl-cases/dashboard/content.ts

welsh translation for tasklist and 1 missing translation on C100 journey

---

src/main/steps/c100-rebuild/check-your-answers/content.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.test.ts
src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.ts
src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts

Revert "bug fixes check your answer"

---

src/main/steps/c100-rebuild/withdraw/confirmation/content.ts
src/main/steps/c100-rebuild/withdraw/confirmation/template.njk

fix (c100-withdrawal-case-status): Fix c100 case withdrawal status update

---

src/main/app/controller/GetCaseController.ts
src/main/steps/tasklistresponse/international-factors/InternationalFactorsGetController.ts
src/main/steps/tasklistresponse/international-factors/InternationalFactorsMapper.test.ts
src/main/steps/tasklistresponse/international-factors/InternationalFactorsMapper.ts
src/main/steps/tasklistresponse/international-factors/InternationalFactorsPostController.test.ts
src/main/steps/tasklistresponse/international-factors/InternationalFactorsPostController.ts

https://tools.hmcts.net/jira/browse/PRL-3490
```
[ ] Yes
[x] No
```

International factors data clean up

---

Jenkinsfile_CNP
src/test/end-to-end/config.js

https://tools.hmcts.net/jira/browse/FPET-419
```
[ ] Yes
[ ] No
```

reverting url migration for citizen frontnd urls

---

src/main/steps/respondent/consent-to-application/ConsentGetController.ts
src/main/steps/respondent/consent-to-application/ConsentMapper.test.ts
src/main/steps/respondent/consent-to-application/ConsentMapper.ts
src/main/steps/respondent/consent-to-application/ConsentPostController.ts

https://tools.hmcts.net/jira/browse/PRL-3510 
- Cleaned up userCase when respondent is on consent to application task list
```
[ ] Yes
[x] No
```

cleaning up respondent consent to application data

---

src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklist-items-all-documents.ts
src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.test.ts
src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts

added test cases for uncovered lines

---

src/main/steps/applicant/upload-document/document-sharing-details/template.njk
src/main/steps/common/common.content.ts
src/main/steps/common/contact-preferences/contact-email/content.test.ts
src/main/steps/common/contact-preferences/contact-email/content.ts
src/main/steps/common/contact-preferences/contact-email/template.njk
src/main/steps/common/contact-preferences/contact-post/content.test.ts
src/main/steps/common/contact-preferences/contact-post/content.ts
src/main/steps/common/contact-preferences/contact-post/template.njk
src/main/steps/common/dashboard-page.njk
src/main/steps/common/page.njk
src/main/steps/common/respondent-summary/content.test.ts
src/main/steps/common/respondent-summary/content.ts
src/main/steps/common/respondent-summary/form.njk
src/main/steps/common/respondent-summary/template.njk
src/main/steps/common/tasklist/template.njk
src/main/steps/common/template.njk
src/main/steps/respondent/yourdocuments/alldocuments/positionstatements/template.njk
src/main/steps/respondent/yourdocuments/alldocuments/yourwitnessstatements/template.njk
src/main/steps/tasklistresponse/summary/content.ts

Common translation infrastructure

---

src/test/end-to-end/config.js
src/test/end-to-end/pages/C100-Rebuild/OtherProceedings.js

Nightly Test - Functional test fix

---

src/main/steps/tasklistresponse/miam/MIAMGetController.test.ts
src/main/steps/tasklistresponse/miam/MIAMGetController.ts
src/main/steps/tasklistresponse/miam/MIAMMapper.test.ts
src/main/steps/tasklistresponse/miam/MIAMMapper.ts
src/main/steps/tasklistresponse/miam/MIAMPostController.ts
src/main/steps/tasklistresponse/utils.ts

refactor(PRL-3602): Refactor MIAM

---

src/test/end-to-end/pages/C100-Rebuild/ApplicantDetails.js
src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
src/test/end-to-end/pages/C100-Rebuild/ChildrenDetails.js
src/test/end-to-end/pages/C100-Rebuild/ConsentOrder.js
src/test/end-to-end/pages/C100-Rebuild/CreateApplication.js
src/test/end-to-end/pages/C100-Rebuild/GoToMiam.js
src/test/end-to-end/pages/C100-Rebuild/HelpWithFees.js
src/test/end-to-end/pages/C100-Rebuild/InternationElement.js
src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
src/test/end-to-end/pages/C100-Rebuild/OtherProceedings.js
src/test/end-to-end/pages/C100-Rebuild/ReasonableAdjustments.js
src/test/end-to-end/pages/C100-Rebuild/RespondentDetails.js
src/test/end-to-end/pages/C100-Rebuild/SafetyConcerns.js
src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js
src/test/end-to-end/pages/C100-Rebuild/UrgencyWithoutNotice.js

Cross Browser and Functional test fixes

---

src/main/app/case/definition.ts
src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringCaseController.test.ts
src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringCaseController.ts
src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringYourCaseService.test.ts
src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringYourCaseService.ts
src/main/steps/respondent/consent-to-application/ConsentMapper.test.ts
src/main/steps/respondent/consent-to-application/ConsentMapper.ts
src/main/steps/respondent/consent-to-application/ConsentPostController.test.ts
src/main/steps/respondent/consent-to-application/ConsentPostController.ts

added changes for consent to application and support during case

---

src/main/steps/applicant/support-you-need-during-case/documents-support/content.test.ts
src/main/steps/applicant/support-you-need-during-case/documents-support/content.ts
src/main/steps/respondent/support-you-need-during-case/documents-support/content.test.ts
src/main/steps/respondent/support-you-need-during-case/documents-support/content.ts
src/main/steps/tasklistresponse/support-you-need-during-case/documents-support/content.test.ts
src/main/steps/tasklistresponse/support-you-need-during-case/documents-support/content.ts

Reverts hmcts/prl-citizen-frontend#925

Revert "test"

---

src/main/steps/applicant/contact-preferences/contact-email/content.test.ts
src/main/steps/applicant/contact-preferences/contact-post/contest.test.ts
src/main/steps/applicant/support-you-need-during-case/documents-support/content.test.ts
src/main/steps/applicant/support-you-need-during-case/documents-support/content.ts
src/main/steps/common/confirm-contact-details/addresshistory/content.ts
src/main/steps/common/contact-preferences/contact-email/content.test.ts
src/main/steps/common/contact-preferences/contact-email/content.ts
src/main/steps/common/contact-preferences/contact-post/content.test.ts
src/main/steps/common/contact-preferences/contact-post/content.ts
src/main/steps/common/keep-details-private/KeepYourDetailsPrivateMapper.ts
src/main/steps/common/summary/utils.ts
src/main/steps/respondent/support-you-need-during-case/documents-support/content.test.ts
src/main/steps/respondent/support-you-need-during-case/documents-support/content.ts
src/main/steps/tasklistresponse/support-you-need-during-case/documents-support/content.test.ts
src/main/steps/tasklistresponse/support-you-need-during-case/documents-support/content.ts
src/main/steps/tasklistresponse/utils.ts

Defect fixes

---

src/main/routes.ts
src/main/steps/applicant/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
src/main/steps/applicant/contact-preferences/contact-preferences/contest.test.ts
src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.test.ts
src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
src/main/steps/common/contact-preferences/ContactPreferencesPostController.test.ts
src/main/steps/common/contact-preferences/ContactPreferencesPostController.ts
src/main/steps/common/contact-preferences/contact-preferences/content.test.ts
src/main/steps/common/contact-preferences/contact-preferences/content.ts

Contact preferences post controller changes

---

Jenkinsfile_CNP
src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
src/test/end-to-end/tests/C100Flow-Master.js
src/test/end-to-end/tests/C100Rebuild-BaseFlow.js
src/test/end-to-end/tests/C100Rebuild-MiamDocumentFlow.js
src/test/end-to-end/tests/C100Rebuild-OtherProceedingsFlow.js
src/test/end-to-end/tests/C100Rebuild-WithAgreement.js
src/test/end-to-end/tests/C100Rebuild-WithUrgencyFlow.js
src/test/end-to-end/tests/CurrentOrPreviousProceedings.js
src/test/end-to-end/tests/InternationalElement.js
src/test/end-to-end/tests/SupportYouNeedDuringYourCase.js
src/test/end-to-end/tests/SupportYouNeedDuringYourCaseApplicant.js
src/test/end-to-end/tests/SupportYouNeedDuringYourCaseRespondent.js

removed pa11y test from master

---

src/main/app/case/case.ts
src/main/modules/oidc/index.ts
src/main/steps/common/app-survey/appSurveyController.ts
src/main/steps/complete-your-application-guidance/routeGuard.test.ts
src/main/steps/complete-your-application-guidance/routeGuard.ts
src/main/steps/complete-your-application-legal-representative/content.test.ts
src/main/steps/complete-your-application-legal-representative/content.ts
src/main/steps/complete-your-application-legal-representative/template.njk
src/main/steps/complete-your-application-paper-form/template.njk
src/main/steps/contact-legal-representative/content.test.ts
src/main/steps/contact-legal-representative/content.ts
src/main/steps/contact-legal-representative/template.njk
src/main/steps/legal-representative-proceedings/content.test.ts
src/main/steps/legal-representative-proceedings/content.ts
src/main/steps/legal-representative-proceedings/template.njk
src/main/steps/screeningQuestionsSequence.test.ts
src/main/steps/screeningQuestionsSequence.ts
src/main/steps/urls.ts

feat(PRL-3701): Add screening questions

---

charts/prl-citizen-frontend/values.preview.template.yaml
package.json
src/main/assets/js/cookie.ts
src/main/assets/js/data-layer.ts
src/main/assets/js/index.ts
src/main/modules/helmet/index.ts
src/main/steps/common/common.content.ts
src/main/steps/common/dashboard-page.njk
src/main/steps/common/page.njk
src/main/steps/cookie-banner/template.njk
src/main/steps/cookies/template.njk
yarn.lock

feat(prl:3693 : Done inital setup for google analytics)

---

src/main/app/case/case.ts
src/main/steps/application-within-proceedings/help-with-fees/content.test.ts
src/main/steps/application-within-proceedings/help-with-fees/content.ts
src/main/steps/application-within-proceedings/help-with-fees/reference/content.test.ts
src/main/steps/application-within-proceedings/help-with-fees/reference/content.ts
src/main/steps/application-within-proceedings/help-with-fees/reference/template.njk
src/main/steps/application-within-proceedings/help-with-fees/template.njk
src/main/steps/application-within-proceedings/utils.ts
src/main/steps/applicationWithinProceedingsSequence.ts
src/main/steps/urls.ts

Help with fees and HWF reference screen

---

src/test/end-to-end/tests/C100Rebuild-MiamDocumentFlow.js

comment FT temporary as it's failing

---

src/main/modules/oidc/index.ts

fix:(testingsupport-ldflag): Fix testingsupport ld flag implementation

---

src/test/end-to-end/pages/C100-Rebuild/ApplicantDetails.js
src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js

ft test issues

---

src/test/end-to-end/config.js
src/test/end-to-end/pages/LoginPage.js
src/test/end-to-end/pages/RespondentEvents.js
src/test/end-to-end/steps_file.js
src/test/end-to-end/tests/C100Respondent-Flow.js
src/test/end-to-end/tests/C100RespondentAboutYou-Flow.js

C100 Respondent Event Workflow

---

src/main/steps/application-within-proceedings/document-upload/content.test.ts
src/main/steps/application-within-proceedings/document-upload/content.ts
src/main/steps/application-within-proceedings/document-upload/postController.test.ts
src/main/steps/application-within-proceedings/document-upload/postController.ts
src/main/steps/application-within-proceedings/document-upload/routeGuard.test.ts
src/main/steps/application-within-proceedings/document-upload/routeGuard.ts
src/main/steps/application-within-proceedings/document-upload/template.njk
src/main/steps/common/fileupload/macro-v1.njk

feat(PRL-4002): Add file upload design update

---

src/main/steps/home/get.test.ts

master sonar fix

---

Jenkinsfile_CNP

Disabling PACT test as it is breaking the pipeline quite often. We will continue working on PACT test behind the scene
```
[ ] Yes
[x] No
```

Disable Pact test

---

src/main/modules/oidc/index.ts
src/main/steps/urls.ts

Fix - Fixed redirecting to confirmation page on successful payment

---

config/development.yaml
src/main/modules/properties-volume/index.ts

secret changes from demo to aat

---

config/development.yaml
src/main/app/case/CosApiClient.test.ts
src/main/app/case/CosApiClient.ts
src/main/app/case/case.ts
src/main/app/case/definition.ts
src/main/steps/application-within-proceedings/agreement-for-request/content.ts
src/main/steps/application-within-proceedings/document-upload/content.ts
src/main/steps/application-within-proceedings/download-form/content.ts
src/main/steps/application-within-proceedings/guidance/content.ts
src/main/steps/application-within-proceedings/guidance/routeGuard.test.ts
src/main/steps/application-within-proceedings/guidance/routeGuard.ts
src/main/steps/application-within-proceedings/help-with-fees/apply-for-hwf/content.ts
src/main/steps/application-within-proceedings/help-with-fees/content.ts
src/main/steps/application-within-proceedings/help-with-fees/reference/content.ts
src/main/steps/application-within-proceedings/help-with-fees/routeGuard.test.ts
src/main/steps/application-within-proceedings/help-with-fees/routeGuard.ts
src/main/steps/application-within-proceedings/inform-other-parties/content.ts
src/main/steps/application-within-proceedings/list-of-applications/content.ts
src/main/steps/application-within-proceedings/list-of-applications/routeGuard.test.ts
src/main/steps/application-within-proceedings/list-of-applications/routeGuard.ts
src/main/steps/application-within-proceedings/navigationController.test.ts
src/main/steps/application-within-proceedings/navigationController.ts
src/main/steps/application-within-proceedings/supporting-document-upload/content.ts
src/main/steps/application-within-proceedings/supporting-documents/content.ts
src/main/steps/application-within-proceedings/upload-your-application/content.ts
src/main/steps/application-within-proceedings/urgent-request/content.ts
src/main/steps/application-within-proceedings/utils.test.ts
src/main/steps/application-within-proceedings/utils.ts
src/main/steps/applicationWithinProceedingsSequence.test.ts

feat(PRL-4055): Integrate Fee-code API for AWP

---

config/development.yaml
src/main/modules/payments/paymentApi.test.ts
src/main/modules/payments/paymentApi.ts
src/main/modules/payments/paymentController.ts

update create payment

---

.github/renovate.json

Renovate Inclusion

---

src/test/end-to-end/pages/FL-401Applicant/ApplicantAboutYouFL401.js
src/test/end-to-end/tests/FL401ApplicantAboutYou-Flow.js

E2E FL401 Respondent Flow

---

charts/prl-citizen-frontend/Chart.yaml
charts/prl-citizen-frontend/values.preview.template.yaml
charts/prl-citizen-frontend/values.yaml
config/custom-environment-variables.yaml
config/default.yaml
config/development.yaml
src/main/app/case/case.ts
src/main/app/case/definition.ts
src/main/app/utils/featureToggles.ts
src/main/modules/oidc/index.ts
src/main/modules/reasonable-adjustements/controller.test.ts
src/main/modules/reasonable-adjustements/controller.ts
src/main/modules/reasonable-adjustements/index.ts
src/main/modules/reasonable-adjustements/interface.ts
src/main/modules/reasonable-adjustements/route.ts
src/main/modules/reasonable-adjustements/service.ts
src/main/server.ts
src/main/steps/common/reasonable-adjustements/confirmation/content.ts
src/main/steps/common/reasonable-adjustements/confirmation/template.njk
src/main/steps/common/reasonable-adjustements/guidance/content.ts
src/main/steps/common/reasonable-adjustements/guidance/template.njk
src/main/steps/common/reasonable-adjustements/utils.ts
src/main/steps/common/task-list/components/tasklist/content.ts
src/main/steps/urls.ts

PRL-4360
Add foundation framework inn CUI for RA common component integration.
```
[ ] Yes
[x] No
```

feat(PRL-4360): Add foundation framework for RA common component

---

audit.json

suppress security warning

---

audit.json
package.json
src/test/end-to-end/codecept.smoke.conf.js
src/test/end-to-end/tests/C100Flow-Master.js

- [X ] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/PRL-4427
```
[ ] Yes
[ ] No
```

Add smoke test coverage

---

src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
src/main/steps/common/task-list/components/tasklist/config/da_respondent.ts
src/main/steps/common/task-list/content.ts
src/main/steps/common/task-list/utils.ts
src/main/steps/tasklistresponse/utils.ts

Handle task list when legal rep is set during case progression.
```
[ ] Yes
[ x] No
```

HotFix- Handle task list when legal rep is set during  case progression

---

charts/prl-citizen-frontend/Chart.yaml
charts/prl-citizen-frontend/values.yaml

NA
Its a config change for citizen to have max pods as 2 instead of 5 which was not required.
```
[ ] Yes
[x] No
```

Max Replicas needed only 2

---

src/main/modules/oidc/index.ts
src/main/steps/applicant/confirm-contact-details/addressdetails/template.njk
src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
src/main/steps/common/summary/utils.ts
src/main/steps/respondent/confirm-contact-details/addressdetails/template.njk

"complete this section" for empty DOB and Address history

---

src/main/app/case/C100CaseApi.ts
src/main/app/case/definition.ts
src/main/app/controller/GetCaseController.test.ts
src/main/app/controller/GetController.test.ts
src/main/app/utils/progress-bar-utils.test.ts
src/main/app/utils/progress-bar-utils.ts
src/main/steps/applicant/support-you-need-during-case/summary/content.ts
src/main/steps/applicant/task-list/utils.test.ts
src/main/steps/c100-rebuild/check-your-answers/content.ts
src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.test.ts
src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
src/main/steps/common/summary-international/utils.ts
src/main/steps/common/summary/utils.test.ts
src/main/steps/common/summary/utils.ts
src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
src/main/steps/common/task-list/components/notification-banner/index.test.ts
src/main/steps/common/task-list/components/progress-bar/config/ca_respondent.ts
src/main/steps/common/task-list/components/progress-bar/index.test.ts
src/main/steps/common/task-list/content.test.ts
src/main/steps/prl-cases/dashboard/utils.test.ts
src/main/steps/tasklistresponse/legalrepresentation/start/LegalRepresentationGetController.test.ts
src/main/steps/tasklistresponse/start/utils.test.ts

Fixes for critical and major sonar issues

---

src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/content.test.ts
src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/content.ts
src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/template.njk

PRL-5549: Hotfix to update providing-evidence screen

---

charts/prl-citizen-frontend/values.preview.template.yaml
src/main/steps/c100-rebuild/check-your-answers/content.ts
src/main/steps/c100-rebuild/miam/no-access-to-mediator/content.test.ts
src/main/steps/c100-rebuild/miam/no-access-to-mediator/content.ts

https://tools.hmcts.net/jira/browse/PRL-5558
Update welsh content as per PO comments
```
[ ] Yes
[x] No
```

PRL-5558: Fix welsh content

---

src/main/modules/payments/paymentController.ts

quick fix draft doc download
```
[ ] Yes
[ ] No
```

quick fix draft doc download

---

src/main/steps/c100-rebuild/start/content.ts

https://tools.hmcts.net/jira/browse/PRL-6071
Page title- Before you start your application - not appearing in Welsh
```
[ ] Yes
[x] No
```

PRL-6071: Page title- Before you start your application - not appearing in Welsh

---

charts/prl-citizen-frontend/values.preview.template.yaml
charts/prl-citizen-frontend/values.yaml

Redis setup

---

src/main/modules/properties-volume/index.ts
src/main/steps/common/statement-of-service/upload/postController.test.ts
src/main/steps/common/statement-of-service/upload/postController.ts
src/main/steps/common/statement-of-service/upload/template.njk

SOS missing error

---

config/development.yaml
src/main/app/case/case.ts
src/main/app/case/definition.ts
src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
src/main/steps/c100-rebuild/applicant/add-applicants/content.ts
src/main/steps/c100-rebuild/applicant/add-applicants/getController.ts
src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
src/main/steps/c100-rebuild/child-details/add-children/content.test.ts
src/main/steps/c100-rebuild/child-details/add-children/content.ts
src/main/steps/c100-rebuild/child-details/other-children/names/content.test.ts
src/main/steps/c100-rebuild/child-details/other-children/names/content.ts
src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.test.ts
src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.ts
src/main/steps/c100-rebuild/other-proceedings/order-details/content.test.ts
src/main/steps/c100-rebuild/other-proceedings/order-details/content.ts
src/main/steps/c100-rebuild/other-proceedings/order-details/postController.ts
src/main/steps/c100-rebuild/people/AddPeoplePostContoller.ts
src/main/steps/c100-rebuild/people/util.ts
src/main/steps/c100-rebuild/respondent-details/add-respondents/content.test.ts
src/main/steps/c100-rebuild/respondent-details/add-respondents/content.ts
src/main/steps/tasklistresponse/proceedings/order-details/content.test.ts
src/main/steps/tasklistresponse/proceedings/order-details/content.ts
src/main/steps/tasklistresponse/proceedings/order-details/postController.ts
src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js

https://tools.hmcts.net/jira/browse/PRL-6201
PRL-6201: Fix Focus Positioning/DAC_Focus_Positioning_01 for DAC
```
[ ] Yes
[x] No
```

feat(6201): DAC fix - Focus Positioning/DAC_Focus_Positioning_01

---

src/main/assets/scss/main.scss
src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/template.njk
src/main/steps/c100-rebuild/miam/miam-excemptions-summary/template.njk
src/main/steps/common/task-list/components/tasklist/tasklist.macro.njk
src/main/steps/common/task-list/template.njk
src/main/steps/tasklistresponse/start/template.njk

https://tools.hmcts.net/jira/browse/PRL-6269
PRL-6269: DAC - Invalid List Structure/DAC_Invalid_List_Structure_01
```
[ ] Yes
[x] No
```

feat(PRL-6269): Fix DAC - Invalid List Structure/DAC_Invalid_List_Structure_01

---

src/main/app/case/definition.ts
src/main/steps/applicant/applicantCaseSequence.ts
src/main/steps/applicant/confirm-contact-details/addressconfirmation/content.test.ts
src/main/steps/common/components/address-manual.test.ts
src/main/steps/common/components/address-manual.ts
src/main/steps/common/confirm-contact-details/addressconfirmation/content.test.ts
src/main/steps/common/confirm-contact-details/addressconfirmation/content.ts
src/main/steps/common/confirm-contact-details/checkanswers/content.ts
src/main/steps/common/confirm-contact-details/contactdetails/content.ts
src/main/steps/common/confirm-contact-details/personaldetails/content.ts
src/main/steps/common/task-list/components/tasklist/content.ts
src/main/steps/common/task-list/components/tasklist/index.test.ts
src/main/steps/respondent/confirm-contact-details/addressconfirmation/content.test.ts
src/main/steps/respondent/respondentcaseSequence.ts
src/main/steps/tasklistresponse/summary/content.ts

feat(PRL-6075): Dashboard journey changes

---

charts/prl-citizen-frontend/values.yaml

fix: update secrets

---

src/main/steps/common/refuge/navigationController.ts
src/main/steps/common/refuge/staying-in-refuge/postController.ts
src/main/steps/common/refuge/upload-refuge-doc/postController.ts
src/main/steps/common/refuge/utils.ts
src/main/steps/common/statement-of-service/upload/postController.ts
src/main/steps/common/statement-of-service/utils.test.ts
src/main/steps/common/statement-of-service/utils.ts

C8 refuge sonar fixes

---

package.json
src/main/modules/error-handler/index.ts
src/main/modules/i18n/index.ts
yarn-audit-known-issues
yarn.lock

https://tools.hmcts.net/jira/browse/PRL-6716
fix(PRL-6716-build-issue): Fix build issue
```
[ ] Yes
[x] No
```

fix(PRL-6716-build-issue): Fix build issue

---

package.json
yarn-audit-known-issues
yarn.lock

fix aks deploy

---

src/main/modules/nunjucks/index.ts
src/main/steps/common/dashboard-page.njk
src/main/steps/common/page.njk
src/main/steps/common/views/includes/script-dt_rum.njk

https://tools.hmcts.net/jira/browse/PRL-6755
PRL-6755: Citizen - Dynatrace Prod RUM configuration for Citizen UI
```
[ ] Yes
[x] No
```

feat(PRL-6755): Integrate DT RUM based on environment

---

Jenkinsfile_CNP

No Jira
Update url to staging aat in Jenkins file

Update url to staging aat in Jenkins file

---

Jenkinsfile_CNP
src/test/end-to-end/pages/C100-Rebuild/ApplicantDetails.js
src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js

No JIIRA
Update TEST URL back to AAT and comment the test checks for C8 refuge screens as these screens are not available until Changes are deployed in AAT

Update TEST URL back to aat

---

src/main/app/controller/GetController.ts
src/main/modules/oidc/index.ts
src/main/steps/c100-rebuild/consent-order/upload/getController.ts
src/main/steps/common/task-list/controllers/CaseDetailsGetController.test.ts
src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
src/main/steps/common/utils.ts
src/main/steps/urls.ts

https://tools.hmcts.net/jira/browse/PRL-6569
PRL-6569: Fix fortify issues
```
[ ] Yes
[x] No
```

Fortify fixes

---

src/main/app/controller/GetController.ts
src/main/app/utils/progress-bar-utils.test.ts
src/main/modules/oidc/index.ts
src/main/steps/applicant/task-list/index.test.ts
src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.test.ts
src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
src/main/steps/c100-rebuild/childaddress/postController.ts
src/main/steps/c100-rebuild/consent-order/upload/getController.ts
src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
src/main/steps/common/refuge/upload-refuge-document/postController.ts
src/main/steps/common/statement-of-service/upload/postController.ts
src/main/steps/common/task-list/controllers/CaseDetailsGetController.test.ts
src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
src/main/steps/common/task-list/controllers/TaskListGetController.test.ts
src/main/steps/common/utils.ts
src/main/steps/tasklistresponse/start/routeGuard.test.ts
src/main/steps/tasklistresponse/summary/postController.test.ts
src/main/steps/urls.ts

https://tools.hmcts.net/jira/browse/PRL-6808
Fixes sonar issues, duplications and improves coverage.
```
[ ] Yes
[x] No
```

PRL-6808: Fix sonar issues

---

src/main/app/auth/service/get-service-auth-token.integration.test.ts
src/main/app/auth/service/get-service-auth-token.ts

update s2s token endpoint

---

charts/prl-citizen-frontend/values.preview.template.yaml
config/development.yaml
src/main/modules/properties-volume/index.ts
src/main/steps/common/dashboard-page.njk
src/main/steps/common/page.njk
src/main/steps/common/task-list/components/notification-banner/index.test.ts
src/main/steps/common/task-list/components/notification-banner/utils.ts
src/main/steps/common/task-list/components/progress-bar/config/ca_applicant.ts
src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
src/main/steps/common/task-list/utils.ts

Fixes the tasklist when the back button is used to return before the case has been created in the backend.
```
[ ] Yes
[x] No
```

Fix tasklist when returning before the case is created

---

.github/renovate.json
.github/stale.yml

FPVTL-80
```
[ ] Yes
[x] No
```

FPVTL-80-renovate

---

src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
src/main/steps/c100-rebuild/validation/util.ts
src/main/steps/common/CaseDataController.test.ts
src/main/steps/common/CaseDataController.ts
src/main/steps/common/task-list/components/progress-bar/config/c100-case-creation.ts
src/main/steps/common/task-list/components/progress-bar/content.ts

This PR is about the Value Add to the citizen journey and has been captured at 
https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1791336934#DTSFamilyPrivateLawKT-C100linearjourney:
```
[ ] Yes
[ ] No
```

Fix VA issues

---

src/main/steps/common/reasonable-adjustments/intro/content.test.ts
src/main/steps/common/reasonable-adjustments/intro/content.ts
src/main/steps/common/reasonable-adjustments/language-requirements-and-special-arrangements/review/content.test.ts
src/main/steps/common/reasonable-adjustments/language-requirements-and-special-arrangements/review/content.ts

https://tools.hmcts.net/jira/browse/PRL-6112
Adds missing welsh content for RA intro and review screens
```
[ ] Yes
[x] No
```

PRL-6112: Add missing welsh content for RA
